name: clip
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - cudatoolkit=11.8.0
  - freeglut=3.4.0
  - freetype=2.13.3
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - pillow=11.1.0
  - pip=25.1
  - pysocks=1.7.1
  - python=3.10.4
  - pytorch-mutex=1.0
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - addict==2.4.0
    - albucore==0.0.24
    - albumentations==2.0.8
    - annotated-types==0.7.0
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - einops==0.8.1
    - filelock==3.18.0
    - fonttools==4.58.2
    - fsspec==2025.5.1
    - ftfy==6.3.1
    - huggingface-hub==0.32.4
    - imageio==2.37.0
    - joblib==1.5.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - lxml==5.4.0
    - matplotlib==3.10.3
    - mmcls==0.25.0
    - mmcv-full==1.7.1
    - mmsegmentation==0.30.0
    - networkx==3.4.2
    - numpy==2.0.1
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - packaging==25.0
    - pandas==2.3.0
    - platformdirs==4.3.8
    - prettytable==3.16.0
    - protobuf==6.31.1
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - safetensors==0.5.3
    - scikit-image==0.25.2
    - scikit-learn==1.7.0
    - scipy==1.15.3
    - seaborn==0.13.2
    - simsimd==6.4.9
    - six==1.17.0
    - stringzilla==3.12.5
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - timm==1.0.15
    - tomli==2.2.1
    - torch==1.12.1+cu116
    - torchvision==0.13.1+cu116
    - tornado==6.5.1
    - tqdm==4.67.1
    - ttach==0.0.3
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - visdom==0.2.4
    - wcwidth==0.2.13
    - websocket-client==1.8.0
    - yapf==0.43.0